apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petclinic-alerts
  namespace: monitoring
spec:
  groups:
  - name: petclinic.rules
    rules:

    - alert: PodRestartHigh
      expr: increase(kube_pod_container_status_restarts_total{pod=~"petclinic.*"}[5m]) > 3
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarting frequently"
        description: "Pod {{ $labels.pod }} restarted multiple times"

    - alert: PodNotReady
      expr: kube_pod_status_ready{condition="false",pod=~"petclinic.*"} == 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod not ready"
        description: "Pod {{ $labels.pod }} is not ready"

    - alert: HighCPUUsage
      expr: (sum(rate(container_cpu_usage_seconds_total{container!="",pod=~"petclinic.*"}[2m])) by (pod) 
             / sum(kube_pod_container_resource_requests_cpu_cores{pod=~"petclinic.*"}) by (pod)) * 100 > 80
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "Pod {{ $labels.pod }} CPU > 80%"

    - alert: HighMemoryUsage
      expr: (container_memory_usage_bytes{pod=~"petclinic.*"} 
             / kube_pod_container_resource_limits_memory_bytes{pod=~"petclinic.*"}) * 100 > 85
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Pod {{ $labels.pod }} memory > 85%"

    - alert: PodDown
      expr: up{pod=~"petclinic.*"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod is down"
        description: "Pod {{ $labels.pod }} is not running"
